title: "Robert Mischuda"
description: "Senior Product Designer â€“ Portfolio"
baseurl: "/portfolio"
url: "https://artavenue.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - "*.bak"
  - "projects_old"
  - "Gemfile"
  - "Gemfile.lock"
